# Generated by Django 2.0.5 on 2018-05-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial_add_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand']},
        ),
    ]
